[build]
 command = "npm install lodash@4.17.20 && npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
 node_bundler = "esbuild"
    external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  [[plugins]]
  package = "@netlify/plugin-functions-install-core"
